name: Cypress Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  
  production-plan:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{ vars.TEST_USER_NAME }}
      PASSWORD: ${{ vars.TEST_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress test file
        run: npx cypress run --spec "cypress/e2e/quotation.cy.js" --config-file=./cypress.config.cjs

  # material-request:
  #   runs-on: ubuntu-latest
  #   needs: production-plan
  #   env:
  #     USER_NAME: ${{ vars.TEST_USER_NAME }}
  #     PASSWORD: ${{ vars.TEST_PASSWORD }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Install Cypress
  #       run: npm install cypress --save-dev

  #     - name: Run Cypress test file 
  #       run: npx cypress run --spec "cypress/e2e/quotation.cy.js" --config-file=./cypress.config.cjs

  # workorder:
  #   runs-on: ubuntu-latest
  #   needs: material-request
  #   env:
  #     USER_NAME: ${{ vars.TEST_USER_NAME }}
  #     PASSWORD: ${{ vars.TEST_PASSWORD }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Install Cypress
  #       run: npm install cypress --save-dev

  #     - name: Run Cypress test file 
  #       run: npx cypress run --spec "cypress/e2e/quotation.cy.js" --config-file=./cypress.config.cjs

  # jobcard:
  #   runs-on: ubuntu-latest
  #   needs: workorder
  #   env:
  #     USER_NAME: ${{ vars.TEST_USER_NAME }}
  #     PASSWORD: ${{ vars.TEST_PASSWORD }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Install Cypress
  #       run: npm install cypress --save-dev

  #     - name: Run Cypress test file 
  #       run: npx cypress run --spec "cypress/e2e/quotation.cy.js" --config-file=./cypress.config.cjs